# Generated by Django 2.2.1 on 2019-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gear", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="geartype",
            name="name",
            field=models.CharField(default="express", max_length=64),
            preserve_default=False,
        )
    ]
