# Generated by Django 2.2.1 on 2019-05-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GearType',
            new_name='GearCategory',
        ),
    ]
