# Generated by Django 2.2.1 on 2019-05-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20190507_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='model_name',
            new_name='make',
        ),
    ]
