# Generated by Django 2.2.1 on 2019-05-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_geartype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='model_name',
        ),
        migrations.AddField(
            model_name='modelname',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gear.Company'),
            preserve_default=False,
        ),
    ]
