# Generated by Django 2.2.1 on 2019-05-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20190525_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='gear_type',
            new_name='gear_category',
        ),
    ]
