# Generated by Django 2.2.1 on 2019-05-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_auto_20190507_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='company',
            new_name='brand',
        ),
    ]
