# Generated by Django 2.2.1 on 2019-06-05 16:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_auto_20190525_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='gearcategory',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
