# Generated by Django 2.2.1 on 2019-05-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_auto_20190505_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField()),
                ('location', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='gear',
            name='image',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='used',
        ),
        migrations.AddField(
            model_name='image',
            name='gear',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gear.Gear'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DateTimeLocation',
        ),
        migrations.AddField(
            model_name='usage',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.Gear'),
        ),
    ]
